<?php
/**
 * Created by PhpStorm.
 * User: evisu
 * Date: 2018/7/3
 * Time: 下午1:58
 */

namespace App\Models;

class TeamModel extends DaoModel
{
    protected $table = 'team';
    protected $casts = [
        'enabled'   => 'boolean'
    ];

    public function addTeam($name, $en_name = '', $icon = '') {
        return $this->addRec(compact('name', 'en_name', 'icon'));
    }

    public function setRecEnabled($id, $enabled) {
        return parent::setRecEnabled($id, $enabled); // TODO: Change the autogenerated stub
    }
}