<?php
/**
 * Created by PhpStorm.
 * User: evisu
 * Date: 2018/7/3
 * Time: 下午1:58
 */

namespace App\Models;

class UserModel extends DaoModel
{
    protected $table = 'user';
    protected $casts = [
        'enabled'   => 'boolean'
    ];

    public function addUser($nickname, $phone, $wechat_id, $location = '') {
        return $this->addRec(compact('nickname', 'phone', 'wechat_id', 'location'));
    }

    public function setRecEnabled($id, $enabled) {
        return parent::setRecEnabled($id, $enabled); // TODO: Change the autogenerated stub
    }
}